# Generated by Django 3.2.16 on 2022-11-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coach',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
